#------------------------------------------------------------------------------
#   Makefile for MOXA UPort series drvier
#-------------------------------------------------------------------------------
obj-$(CONFIG_USB_SERIAL_MXUSBSERIAL) += mxbus.o mxusb-serial.o


